spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    com.mysql.cj.jdbc.Driver

  flyway:
    locations: classpath:db/migration, classpath:db/data
