server:
  port: 8080

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
